using HomeSeerAPI;
using NullGuard;
using Scheduler;
using System;
using System.Collections.Specialized;
using System.Text;
using System.Web;

namespace Hspi
{
    using static System.FormattableString;

    /// <summary>
    /// Helper class to generate configuration page for plugin
    /// </summary>
    /// <seealso cref="Scheduler.PageBuilderAndMenu.clsPageBuilder" />
    [NullGuard(ValidationFlags.Arguments | ValidationFlags.NonPublic)]
    internal class ConfigPage : PageBuilderAndMenu.clsPageBuilder
    {
        protected const string IdPrefix = "id_";

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigPage" /> class.
        /// </summary>
        /// <param name="HS">The hs.</param>
        /// <param name="pluginConfig">The plugin configuration.</param>
        public ConfigPage(IHSApplication HS, PluginConfig pluginConfig) : base(pageName)
        {
            this.HS = HS;
            this.pluginConfig = pluginConfig;
        }

        /// <summary>
        /// Gets the name of the web page.
        /// </summary>
        public static string Name => pageName;

        /// <summary>
        /// Get the web page string for the configuration page.
        /// </summary>
        /// <returns>
        /// System.String.
        /// </returns>
        public string GetWebPage()
        {
            try
            {
                reset();

                AddHeader(HS.GetPageHeader(Name, "Configuration", string.Empty, string.Empty, false, false));

                System.Text.StringBuilder stb = new System.Text.StringBuilder();
                stb.Append(PageBuilderAndMenu.clsPageBuilder.DivStart("pluginpage", ""));
                stb.Append(BuildWebPageBody());
                stb.Append(PageBuilderAndMenu.clsPageBuilder.DivEnd());
                AddBody(stb.ToString());

                AddFooter(HS.GetPageFooter());
                suppressDefaultFooter = true;

                return BuildPage();
            }
            catch (Exception)
            {
                return "error";
            }
        }

        /// <summary>
        /// The user has selected a control on the configuration web page.
        /// The post data is provided to determine the control that initiated the post and the state of the other controls.
        /// </summary>
        /// <param name="data">The post data.</param>
        /// <param name="user">The name of logged in user.</param>
        /// <param name="userRights">The rights of the logged in user.</param>
        /// <returns>Any serialized data that needs to be passed back to the web page, generated by the clsPageBuilder class.</returns>
        public string PostBackProc(string data, [AllowNull]string user, int userRights)
        {
            NameValueCollection parts = HttpUtility.ParseQueryString(data);

            string form = parts["id"];

            if (form == NameToIdWithPrefix(SaveButtonName))
            {
                StringBuilder results = new StringBuilder();

                // Validate
                if (string.IsNullOrWhiteSpace(parts[APIKeyId]))
                {
                    results.AppendLine("API Key is not Valid.<br>");
                }

                if (string.IsNullOrWhiteSpace(parts[StationId]))
                {
                    results.AppendLine("Station is not Valid.<br>");
                }

                uint refreshIntervalMinutes = 0;
                if (string.IsNullOrWhiteSpace(parts[RefreshIntervalId]) ||
                    !uint.TryParse(parts[RefreshIntervalId], out refreshIntervalMinutes) ||
                    refreshIntervalMinutes > int.MaxValue)
                {
                    results.AppendLine("Refresh Interval is not Valid.<br>");
                }

                Unit unit = Unit.US;
                if (string.IsNullOrWhiteSpace(parts[UnitId]) ||
                    !System.Enum.TryParse<Unit>(parts[UnitId], out unit))
                {
                    results.AppendLine("Unit is not Valid.<br>");
                }
                if (results.Length > 0)
                {
                    this.divToUpdate.Add(ErrorDivId, results.ToString());
                }
                else
                {
                    this.divToUpdate.Add(ErrorDivId, string.Empty);
                    this.pluginConfig.APIKey = parts[APIKeyId];
                    this.pluginConfig.RefreshIntervalMinutes = (int)refreshIntervalMinutes;
                    this.pluginConfig.StationId = parts[StationId];
                    this.pluginConfig.Unit = unit;
                    this.pluginConfig.DebugLogging = parts[DebugLoggingId] == "checked";
                    this.pluginConfig.FireConfigChanged();
                }

                this.divToUpdate.Add(ImageDivId, GetImageHtml());
                this.divToUpdate.Add(CallsPerDayId, GetCallsPerDay());
            }
            else
            {
                bool changed = false;
                foreach (var deviceDefintion in WUWeatherData.DeviceDefinitions)
                {
                    foreach (var childDeviceDefinition in deviceDefintion.Children)
                    {
                        string id = NameToId(deviceDefintion, childDeviceDefinition);
                        string value = parts[id];

                        if (value != null)
                        {
                            this.pluginConfig.SetDeviceEnabled(deviceDefintion, childDeviceDefinition, value == "checked");
                            changed = true;
                        }
                    }
                }
                if (changed)
                {
                    this.pluginConfig.FireConfigChanged();
                }
            }

            return base.postBackProc(Name, data, user, userRights);
        }

        /// <summary>
        /// Builds the web page body for the configuration page.
        /// The page has separate forms so that only the data in the appropriate form is returned when a button is pressed.
        /// </summary>
        private string BuildWebPageBody()
        {
            int i = 0;
            StringBuilder stb = new StringBuilder();

            var tabs = new clsJQuery.jqTabs("tab1id", PageName);
            var tab1 = new clsJQuery.Tab();
            tab1.tabTitle = "Settings";
            tab1.tabDIVID = Invariant($"tabs{i++}");
            tab1.tabContent = BuildSettingTab();
            tabs.tabs.Add(tab1);

            foreach (var deviceDefintion in WUWeatherData.DeviceDefinitions)
            {
                var tab = new clsJQuery.Tab();
                tab.tabTitle = deviceDefintion.Name;
                tab.tabDIVID = Invariant($"tabs{i++}");
                tab.tabContent = BuildTab(deviceDefintion);
                tabs.tabs.Add(tab);
            }

            tabs.postOnTabClick = false;
            stb.Append(tabs.Build());

            return stb.ToString();
        }

        private string BuildTab(RootDeviceData root)
        {
            StringBuilder stb = new StringBuilder();
            string idName = NameToId(root.Name);
            stb.Append(PageBuilderAndMenu.clsPageBuilder.FormStart(Invariant($"ftm{idName}"), Invariant($"Id{idName}"), "Post"));

            stb.Append(@"<div>");
            stb.Append(@"<table class='full_width_table'");
            stb.Append("<tr height='5'><td colspan=2></td></tr>");
            stb.Append("<tr><td colspan=2> </td></tr>");
            stb.Append("<tr><td colspan=2><strong>Select devices to be created</strong><td></tr>");
            stb.Append("<tr><td colspan=2> </td></tr>");

            foreach (var childDeviceDefinition in root.Children)
            {
                stb.Append(Invariant($"<tr><td colspan=2>{FormCheckBox(NameToId(root, childDeviceDefinition), childDeviceDefinition.Name, pluginConfig.GetDeviceEnabled(root, childDeviceDefinition))}</td></tr>"));
            }
            stb.Append(@" </table>");
            stb.Append(@"</div>");
            stb.Append(PageBuilderAndMenu.clsPageBuilder.FormEnd());

            return stb.ToString();
        }

        private string GetImageHtml()
        {
            StringBuilder stb = new StringBuilder();
            if (string.IsNullOrWhiteSpace(pluginConfig.StationId))
            {
                stb.Append(Invariant($"<a href='http://www.wunderground.com' target='_blank'><img width='100px' alt='Powered by Weather Underground' src='http://icons.wxug.com/logos/PNG/wundergroundLogo_4c.png'></a>"));
            }
            else
            {
                stb.Append(Invariant($"<a href='http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID={pluginConfig.StationId}' target='_blank'><img src='http://banners.wunderground.com/cgi-bin/banner/ban/wxBanner?bannertype=wxstnsticker_both&weatherstationcount={pluginConfig.StationId}' height='160' width='160' border='0' alt='Weather Underground PWS {pluginConfig.StationId}'/></a>"));
            }

            stb.Append("&nbsp;<a href='https://www.wunderground.com/wundermap' target='_blank'>Find Station</a>");
            return stb.ToString();
        }

        private string GetCallsPerDay()
        {
            if (pluginConfig.RefreshIntervalMinutes != 0)
            {
                return Invariant($"&nbsp; ({ Math.Max(1, 1440 / pluginConfig.RefreshIntervalMinutes)} calls per day)");
            }
            else
            {
                return string.Empty;
            }
        }

        private string BuildSettingTab()
        {
            int unitsSelection = -1;
            var unitsDropDown = new NameValueCollection();
            foreach (var value in Enum.GetValues(typeof(Unit)))
            {
                unitsDropDown.Set(EnumHelper.GetDescription((System.Enum)value), value.ToString());
                if ((Unit)value == pluginConfig.Unit)
                {
                    unitsSelection = unitsDropDown.Count - 1;
                }
            }

            StringBuilder stb = new StringBuilder();
            stb.Append(PageBuilderAndMenu.clsPageBuilder.FormStart("ftmSettings", "IdSettings", "Post"));

            stb.Append(@"<div>");
            stb.Append(@"<table class='full_width_table'");
            stb.Append("<tr height='5'><td style='width:25%'></td><td style='width:20%'></td><td style='width:55%'></td></tr>");
            stb.Append(Invariant($"<tr><td class='tablecell'>APIKey:</td><td class='tablecell' style='width: 50px'>{HtmlTextBox(APIKeyId, pluginConfig.APIKey)}</td><td class='tablecell'>&nbsp;<a href='https://www.wunderground.com/weather/api/' target='_blank'>API Home</a></td></tr>"));
            stb.Append(Invariant($"<tr><td class='tablecell'>Refresh Interval(minutes):</td><td class='tablecell'>{HtmlTextBox(RefreshIntervalId, Invariant($"{pluginConfig.RefreshIntervalMinutes}"))} </ td ><td class='tablecell'><div id={CallsPerDayId}>{GetCallsPerDay()}</div></td></ tr > "));
            stb.Append(Invariant($"<tr><td class='tablecell'>Station:</td><td class='tablecell'>{HtmlTextBox(StationId, Invariant($"{pluginConfig.StationId}"))}</td ><td class='tablecell'><div id='{ImageDivId}'>{GetImageHtml()}</div></td></ tr > "));
            stb.Append(Invariant($"<tr><td class='tablecell'>Unit:</td><td colspan=2 class='tablecell'>{FormDropDown(UnitId, unitsDropDown, unitsSelection, 150, "Units to be used for Device")}</ td ></ tr > "));
            stb.Append(Invariant($"<tr><td class='tablecell'>Debug Logging Enabled:</td><td colspan=2 class='tablecell'>{FormCheckBox(DebugLoggingId, string.Empty, this.pluginConfig.DebugLogging)}</ td ></ tr > "));
            stb.Append(Invariant($"<tr><td colspan=3><div id='{ErrorDivId}' style='color:Red'></div></td><td></td></tr>"));
            stb.Append(Invariant($"<tr><td colspan=3>{FormButton("Save", SaveButtonName, "Save Settings")}</td><td></td></tr>"));
            stb.Append("<tr height='5'><td colspan=3></td></tr>");
            stb.Append(Invariant($"<tr><td colspan=3></td></tr>"));
            stb.Append(@"<tr><td colspan=3><div>Icons made by <a href='http://www.freepik.com' title='Freepik' target='_blank'>Freepik</a> from <a href='http://www.flaticon.com' title='Flaticon' target='_blank'>www.flaticon.com</a> is licensed by <a href='http://creativecommons.org/licenses/by/3.0/' title='Creative Commons BY 3.0' target='_blank'>CC 3.0 BY</a></div></td></tr>");
            stb.Append(@"<tr height='5'><td colspan=3></td></tr>");
            stb.Append(@" </table>");
            stb.Append(@"</div>");
            stb.Append(PageBuilderAndMenu.clsPageBuilder.FormEnd());

            return stb.ToString();
        }

        private static string NameToId(string name)
        {
            return name.Replace(' ', '_');
        }

        private static string NameToIdWithPrefix(string name)
        {
            return Invariant($"{ IdPrefix}{NameToId(name)}");
        }

        private static string NameToId(DeviceDataBase parent, DeviceDataBase child)
        {
            return Invariant($"{NameToId(parent.Name)}_{NameToId(child.Name)}");
        }

        protected static string HtmlTextBox(string name, string defaultText, int size = 25)
        {
            return Invariant($"<input type=\'text\' id=\'{NameToIdWithPrefix(name)}\' size=\'{size}\' name=\'{name}\' value=\'{defaultText}\'>");
        }

        protected string FormDropDown(string name, NameValueCollection options, int selected, int width, string tooltip)
        {
            var dropdown = new clsJQuery.jqDropList(name, PageName, false)
            {
                selectedItemIndex = -1,
                id = NameToIdWithPrefix(name),
                autoPostBack = false,
                toolTip = tooltip,
                style = Invariant($"width: {width}px;"),
                enabled = true
            };

            if (options != null)
            {
                for (var i = 0; i < options.Count; i++)
                {
                    var sel = i == selected;
                    dropdown.AddItem(options.GetKey(i), options.Get(i), sel);
                }
            }

            return dropdown.Build();
        }

        protected string FormCheckBox(string name, string label, bool @checked)
        {
            var checkbox = new clsJQuery.jqCheckBox(name, label, PageName, true, true)
            {
                id = NameToIdWithPrefix(name),
                @checked = @checked,
            };
            return checkbox.Build();
        }

        protected string FormButton(string name, string label, string toolTip)
        {
            var button = new clsJQuery.jqButton(name, label, PageName, true)
            {
                id = NameToIdWithPrefix(name),
                toolTip = toolTip,
            };
            button.toolTip = toolTip;
            button.enabled = true;

            return button.Build();
        }

        private const string SaveButtonName = "Save";
        private const string CallsPerDayId = "CallsPerDayId";
        private const string DebugLoggingId = "DebugLoggingId";
        private const string UnitId = "UnitId";
        private const string APIKeyId = "APIKeyId";
        private const string StationId = "StationId";
        private const string ErrorDivId = "message_id";
        private const string ImageDivId = "image_id";
        private const string RefreshIntervalId = "RefreshIntervalId";
        private static readonly string pageName = Invariant($"{WUWeatherData.PlugInName} Configuration").Replace(' ', '_');
        private readonly IHSApplication HS;
        private readonly PluginConfig pluginConfig;
    }
}